### ISSUE TITLE
KEmulator doesn't work

### ISSUE THREAD

**Issue by arnavbhatt288** [ROS-AppDB/AppForm#2]
Rating - Garbage
Program Author - Unknown
ReactOS Version - ReactOS 0.4.7
What works - It runs can take .jar files
What doesn't work - When it runs the .jar files, it causes ROS to become very slow and unusable
What wasn't tested - NIL
Additional comments - It sometimes crashes the ReactOS.

**Comment by Mcpg** [comment]
What's the version of KEmulator you've used?

**Comment by Hacker1245** [comment]
What .jar file did you use?

**Comment by arnavbhatt288** [comment]
It does work but as soon as you put your .jar file, it gets very slow and system become unusable.

**Comment by arnavbhatt288** [comment]
Uhh it was Bouncing Tales and the version was KEmulator lite 0.9.8.

**Comment by Mcpg** [comment]
Alright, entry posted. I just rewrote it a bit to have it more "grammar friendly", Anyway, thanks for contribution!

**Comment by arnavbhatt288** [comment]
NO PROBLEM

On 14-Jan-2018 2:30 PM, "Paweł Cholewa" <notifications@github.com> wrote:

Alright, entry posted. I just rewrote it a bit to have it more "grammar
friendly", Anyway, thanks for contribution!

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/ROS-AppDB/AppForm/issues/2#issuecomment-357497662>, or mute
the thread
