### ISSUE TITLE
HyperCam 2.29.01

### ISSUE THREAD

**Issue by Hacker1245** [ROS-AppDB/AppForm#3]
Rating: silver
Program author: Hyperionics
ReactOS version: 0.4.8 g7b39851
Test time: 2018/01/09
What works: Video recording
What doesn't work: Sound recording, video compression
What wasn't tested: 
Additional comments: You need to set the video compressor to Full Frames, else it will not work.
Tested on QEMU.

**Comment by Mcpg** [comment]
I forgot to tell that the record is in the database. Thanks for contribution!
