### ISSUE TITLE
Launchy 2.5.0

### ISSUE THREAD

**Issue by Hacker1245** [ROS-AppDB/AppForm#4]
Rating: gold
Program author: Josh Karlin
ReactOS version: 0.4.8 g7b39851
Test time: 2018/01/10
What works: Searching apps and files
What doesn't work: 
1. App has visual glitches, can't see text
2. Weby and Runner plugins do not work

What wasn't tested:
Additional comments:

**Comment by Mcpg** [comment]
Entry posted, thanks for contribution!
