### ISSUE TITLE
Xvid v1.3.5

### ISSUE THREAD

**Issue by Hacker1245** [ROS-AppDB/AppForm#5]
Rating: gold
Program author: Xvid
Program URL: https://www.xvid.com/
ReactOS version: 0.4.8 g7b39851
Test time: 2018/01/10
What works: Encoding and decoding video
What doesn't work: Built in converter, stats graph while encoding
What wasn't tested:
Additional comments: Stats graph  does not work probably due to high CPU usage.
Codec can be used with HyperCam to make smaller files.

**Comment by Mcpg** [comment]
Entry added into DB. Thanks for contribution!
