### ISSUE TITLE
HFS 2.3k

### ISSUE THREAD

**Issue by Hacker1245** [ROS-AppDB/AppForm#6]
Rating: gold
Program author: Massimo Melina
Program URL: http://www.rejetto.com/hfs/?f=intro
ReactOS version: 0.4.8 g9c27193
Test time: 2018/01/27
What works: Nearly all the functions work
What doesn't work: Minimizing does not work, option to close to tray
What wasn't tested: DNS related options, there might be some other options that were not tested.
Additional comments: Bandwidth graph sometimes does not show up.

**Comment by Mcpg** [comment]
Alright, entry in the DB. Thanks for contribution!
