### ISSUE TITLE
Digital Works 3.0.5.0

### ISSUE THREAD

**Issue by Hacker1245** [ROS-AppDB/AppForm#7]
Rating: gold
Program author: Mecanique
Program URL: https://www.mecanique.co.uk/shop/index.php?route=product/category&path=89
ReactOS version: 0.4.11 g3a9fe2b
Test time: 01/11/2018
What works: Basic and advanced circuits from the sample folder work perfectly.
What doesn't work: Logic probe history doesn't seem to work
What wasn't tested: Didn't test every part on the parts list.
Additional comments: Program is laggy when large circuits are used.

**Comment by Mcpg** [comment]
Application added
