### ISSUE TITLE
Microsoft Works SE 9.0

### ISSUE THREAD

**Issue by Hacker1245** [ROS-AppDB/AppForm#8]
Rating: Bronze
Program author: Microsoft
Program URL: https://web.archive.org/web/20090130083822/http://www.microsoft.com:80/PRODUCTS/works/default.mspx
ReactOS version: 0.4.11 g5d91d52
Test time: 03/11/2018
What works: Main program, spreadsheet, database
What doesn't work: Text editor, calendar
What wasn't tested: Didn't test other functions in the main program due to text glitches
Additional comments: Used compatibility mode and changed the registry values from this issue https://jira.reactos.org/browse/CORE-14123. I left the first one blank and changed the second one to WinNT.

**Comment by Mcpg** [comment]
Added
