### ISSUE TITLE
Just Cause 1

### ISSUE THREAD

**Issue by Hacker1245** [ROS-AppDB/AppForm#9]
Rating: Garbage
Program author: Avalanche Studios
Program URL: https://web.archive.org/web/20061128214214/http://www.eidosinteractive.com:80/games/info.html?gmid=163
ReactOS version: 0.4.11 g5d91d52
Test time: 03/11/2018
What works: Setup, config tool
What doesn't work: Main game
What wasn't tested: Didn't test the rest of the game because it can't fully load itself.
Additional comments: I used the CD version of Just Cause 1.

**Comment by Mcpg** [comment]
Added
